/** The commands, one line each; the reference page carries the rest. */
export function usage(version: string): string {
  return [
    `agentsafe ${version}: put an authority boundary in front of any agent or API.`,
    "",
    "Usage: agentsafe <command> [options]",
    "",
    "Gateway",
    "  init                 Write agentsafe.yaml for this directory",
    "  proxy                Run the gateway (--upstream URL, --port N, --mode shadow|enforcement)",
    "  run                  Run the gateway from agentsafe.yaml (same command, file first)",
    "  intercept            Run the transparent interceptor: observe every destination, govern the listed ones",
    "  status               Ask a running gateway what it is doing",
    "  doctor               Check the binary, configuration, upstream, Decionis and credentials",
    "  test                 Show what reaches a target without the boundary and what enforcement prevents",
    "  config               Print the effective configuration and where each setting came from",
    "  login | logout       Store or remove a Decionis key for this user (--provision mints a free workspace)",
    "  version              Print the version",
    "",
    "Evidence",
    "  verify chain [file]  Verify a log's hash chains offline",
    "  verify bundle <dir>  Verify an evidence bundle offline",
    "  verify intent <path> Check Agent-Safe Intent vectors, or hash a binding, offline",
    "",
    "Trusted executor",
    "  serve                Run the proposal executor from the environment",
    "  probe-containment    Report whether a system of record answers the agent zone",
    "",
    "  test [name=host:port]...  also dials each real target: does it answer without the gateway?",
    "",
    "Options shared by proxy, run, status, doctor and config:",
    "  --config <file>  --upstream <url>  --port <n>  --listen <host:port>",
    "  --mode <shadow|enforcement>  --failure-policy <failClosed|failOpen>",
    "  --authority <local|decionis>  --verbose  --json",
    "",
    "Precedence: flags, then environment, then the file, then defaults.",
    "",
  ].join("\n");
}
